### ISSUE TITLE
Improvement of installation documentation

### ISSUE THREAD

**Issue by Nivekiba** [romellfudi/VoIpUSSD#103]
My request is just for the documentation. It's hard to install voipussd if we are a newbie in gradle as Android studio do all for us (regarding gradle)

So it will be nice perhaps to detail your documentation and explain briefly why to add each file where and how it is supposed to give an output

**Additional context**
Maybe describe for differents versions of android should be good. But I think it's too much complicated and unnecessary

Thanks for reading

**Comment by romellfudi** [comment]
sure @Nivekiba , could please add the template for documentation?

**Comment by Nivekiba** [comment]
Sorry to say that but i'm not a very good documented.
Just saying it in order to help to improve.
I think your tool is a very good and useful tool.

**Comment by romellfudi** [comment]
Unfortunately, I am just the one who adds improvements to this library which depends on the device system operation and Country Telcom SIMs. 

I don't have enough devices to test in every environment.

Please consider [donating](https://paypal.me/romellfudi/15) 💸 to help it improve! or just share the project into any Android Social Group!
