### ISSUE TITLE
Not working in Android 13

### ISSUE THREAD

**Issue by kuwrom** [romellfudi/VoIpUSSD#114]
In android 13, you can see a log of the result message in logcat from the ussd call but, the app still waits for a result and doesn't do anything.

**Comment by kuwrom** [comment]
It worked for me after adding a new alert dialog class name
`event.getClassName().equals("cn.nubia.commonui.androidx.appcompat.app.AlertDialog")`

**Comment by romellfudi** [comment]
@kuwrom, could you confirm if the issue is still present on the Android 13 platform?
