### ISSUE TITLE
Samsung with Android 14 USSD issue

### ISSUE THREAD

**Issue by yohaneswilliam12** [romellfudi/VoIpUSSD#117]
## Required Prerequisites for filing a bug
I have issue with USSD call using any samsung with android 14, every ussd callbacks triggered twice

I use this widget for scanning umb automatically, and then parse the number then save to array, then try every menus one by one. I use android 9, 10, 12, and 13 before, and it runs well, but there is a problem when i run in android 14, the callbacks triggered twice, so my scanned array popped twice, this api sent twice request for every dialog, so it fails right away

## Required information

Devices that run smoothly:
Samsung A23 - Android 13
Realme 2 Pro - Android 9
Xiaomi Poco M4 Pro - Android 12
Samsung A53 - Android 12
Samsung S22 - Android 13

Devices that have problem:
Samsung A54 - Android 14
Samsung S21 FE - Android 14
Samsung A23 - Android 14

![WhatsApp Image 2024-05-09 at 00 53 15_bdb66d87](https://github.com/romellfudi/VoIpUSSD/assets/49800188/cabc1ad3-2afe-4a08-aeef-06c76d6e6ff3)

**Comment by romellfudi** [comment]
@yohaneswilliam12 please update your workflow to skip the first windows pop-up

**Comment by romellfudi** [comment]
Are there any updates? @yohaneswilliam12

**Comment by yohaneswilliam12** [comment]
i found solution from https://github.com/romellfudi/VoIpUSSD/issues/115
