### ISSUE TITLE
Second time dialog stays open

### ISSUE THREAD

**Issue by akkastechgithub** [romellfudi/VoIpUSSD#14]
When I run the app the first time everything works smooth. But when I run the app second-time USSD dialog stays open nothing is getting input

**Comment by ducaale** [comment]
`CallbackMessage` is not dusposed of after `callbackInvoke.over` maybe that is the problem?

**Comment by vutranHS** [comment]
> When I run the app the first time everything works smooth. But when I run the app second-time USSD dialog stays open nothing is getting input

How can you fix it ?

**Comment by vutranHS** [comment]
> How do you fix it ?

**Comment by vutranHS** [comment]
> When I run the app the first time everything works smooth. But when I run the app second-time USSD dialog stays open nothing is getting input

Use method sendData() instead of send()

**Comment by ducaale** [comment]
`send()` works for me. which commit are you currently using?

**Comment by romellfudi** [comment]
Hi @akkastechgithub @ducaale @vutranHS ,
To dismiss future issues please use USSDApi interface instead USSDController, [1.1.h](https://github.com/romellfudi/VoIpUSSD/releases/tag/Rev20) :
USSDApi ussdApi = USSDController.getInstance(context); ussdApi.callUSSDInvoke(); ussdApi.send().
