### ISSUE TITLE
AAPT error after adding the implementation in app build.gradle file

### ISSUE THREAD

**Issue by Zeit42** [romellfudi/VoIpUSSD#23]
So I add the following block to my build.gradle file:

> repositories {
>     jcenter()
> }

and then under dependencies, I add:
> implementation 'com.romellfudi.ussdlibrary:ussd-library:1.1.i'

but after syncing, I get this error:

> AGPBI: {"kind":"error","text":"error: attribute \u0027com.agict.voipussd:showAsAction\u0027 not found.","sources":[{"file":"/private/var/root/.gradle/caches/transforms-1/files-1.1/ussd-library-1.1.h.aar/28120cf25a73f1fef28d19fceab7322d/res/menu/menu_activity.xml","position":{"startLine":3}}],"original":"","tool":"AAPT"}

I have tried to proceed and added in the xml file, the permission requests, and the service in the manifest file. I hit Clean and Rebuild but to no avail.

**Comment by romellfudi** [comment]
Try to change your resource's name of menu/menu_activity.xml in your app project

**Comment by romellfudi** [comment]
Hi @Zeit42 , i build a new project and rolling without any problem,
please show me your manifest

**Comment by Zeit42** [comment]
I don't have a res/menu folder where I have xml files for my menus.

This is how my manifest looks like

<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.agict.voipussd">

    <application
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:supportsRtl="true"
        android:theme="@style/AppTheme">

        <activity android:name=".MainActivity">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>

        <service
            android:name="com.romellfudi.ussdlibrary.USSDService"
            android:permission="android.permission.BIND_ACCESSIBILITY_SERVICE">
            <intent-filter>
                <action android:name="android.accessibilityservice.AccessibilityService" />
            </intent-filter>
            <meta-data
                android:name="android.accessibilityservice"
                android:resource="@xml/ussd_service" />
        </service>
        
    </application>

</manifest>

**Comment by romellfudi** [comment]
What android build version did you use? ...
send your main gradle.build

**Comment by romellfudi** [comment]
Hi @Zeit42 , the problem its your android library doesn't load correctly.

**Comment by Zeit42** [comment]
> What android's build version did you use? ...
> 
> Other way clean your cache. android studio => tool bar => clean cache
> 
> _Sent from my Galaxy S8+ using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

How do I check for the android build version? 

Also, I can't find the `clean cache` option. There's either the Invalidate Cache (I don't think it worked), and Clean Project (which I've tried but didn't help).

**Comment by romellfudi** [comment]
Try Invalidate cache, put 1.1.i version

**Comment by Zeit42** [comment]
I tried invalidating and put 1.1.i but still to no avail.

**Comment by romellfudi** [comment]
... i can't help u. that issue its about your local repository.

**Comment by abkoradiya** [comment]
@romellfudi Hi Why you have closed this issue?
There is menu file in your library itself.

**Comment by romellfudi** [comment]
@abkoradiya yes, and there's no a problem . Many android libraries have it

**Comment by abkoradiya** [comment]
> @abkoradiya yes, and there's no a problem . Many android libraries have it  
> What do you want to know?

Yes without appcompat library build fails. Check once.

**Comment by romellfudi** [comment]
Please @abkoradiya create the PR and link to this issue

**Comment by canaan5** [comment]
I am having same error on a new empty project

**Comment by romellfudi** [comment]
Check implementation table , jcenter is deprecated
