### ISSUE TITLE
Some problem configing

### ISSUE THREAD

**Issue by Royz2** [romellfudi/VoIpUSSD#27]
Hello,

Cool API, thank you!

Could you please edit the Readme file to include the correct way to add your library to my project.
I can't seem to understand what is the `latestVersion` to be added to:
    `implementation 'com.romellfudi.ussdlibrary:ussd-library:{latestVersion}'`

Secondly, the examples are written sometimes in Java and the other times in Kotlin.
Please share the complete ways to use the library in every language seperatley.

Again, thanks for this awesome API you created, I've been looking for it for a long time.

Roy

**Comment by romellfudi** [comment]
Hi @Royz2, please look the `budgets` of bintray

**Comment by Royz2** [comment]
![image](https://user-images.githubusercontent.com/51711377/59327614-bcdbb380-8cf2-11e9-994e-a761e475bc53.png)

Hello, thanks for your reply.

It says that the version is `v1.1.i` is it logical?

**Comment by romellfudi** [comment]
@Royz2 definitely that right. 
Add:
```gradle
implementation 'com.romellfudi.ussdlibrary:ussd-library:1.1.i'
```
