### ISSUE TITLE
Getting TX POWER

### ISSUE THREAD

**Issue by Royz2** [romellfudi/VoIpUSSD#28]

**Comment by Royz2** [comment]
Hello!

Is it possible to get TX Power of an Android phone using this library?
If so, please share :+1: 

Thank you

**Comment by romellfudi** [comment]
@Royz2 What is TX Power?

**Comment by Royz2** [comment]
The device's transmission power

**Comment by romellfudi** [comment]
This api don't have any similar association with that.
