### ISSUE TITLE
responseInvoke does not emit first line of message if it starts with a number

### ISSUE THREAD

**Issue by nostupidity** [romellfudi/VoIpUSSD#30]
Hi thank you for your amazing work, I am trying to separate the message by new line but if the first line response starts with a number the `responseInvoke()` ignores the first line and then continue with the following line.

Example USSD Response:
Please choose promo
1 PromoSample1
2 PromoSample2

The response above works as expected but if the USSD response's first line has a number for example:
1 PromoSample1
2 PromoSample2

`responseInvoke()` will emit only "2 PromoSample2" and  ignore "1 PromoSample1"

[Screenshot](https://imgur.com/hhTOUI6)

**Comment by nostupidity** [comment]
I tinkered the code and the problem is with the USSDService class line 58
`response = response.substring(response.indexOf('\n') + 1);`

**Comment by romellfudi** [comment]
Hi @nostupidity , m... that's interesting. However, always depends on the xml from TELCOM. I didn't have that issue, because The TELCOM had sent with a header string.
