### ISSUE TITLE
Is there a cordova plugin ?

### ISSUE THREAD

**Issue by donmbelembe** [romellfudi/VoIpUSSD#32]

**Comment by romellfudi** [comment]
mm.. not sure, but i though is possible call such as whatever android library

**Comment by romellfudi** [comment]
@donmbelembe 
please read and test:
 https://github.com/rmxakalogistik/cordova-plugin-VoIpUSSD
please comment whether  this cordova plugin works correctly

**Comment by donmbelembe** [comment]
Thanks let me check

**Comment by donmbelembe** [comment]
I'm facing an issue please see my issue https://github.com/rmxakalogistik/cordova-plugin-VoIpUSSD/issues/1

**Comment by donmbelembe** [comment]
So I was able to work with the plugin because an unused import was breaking the compilation
https://github.com/rmxakalogistik/cordova-plugin-VoIpUSSD/blob/fbabd67a160cfd180e1959aa6e8a345d04197e8c/src/android/VoIpUSSD.java#L7

And also the plugin contain a lot of trash code, it need a complete rewrite

**Comment by romellfudi** [comment]
this issue was solved with [cordova-plugin-VoIpUSSD](https://github.com/rmxakalogistik/cordova-plugin-VoIpUSSD/issues/1)
