### ISSUE TITLE
The responseInvoke in not being called, it works for java but not work in Kotlin 

### ISSUE THREAD

**Issue by vovoapps** [romellfudi/VoIpUSSD#33]

**Comment by romellfudi** [comment]
mmm which Kotlin version do you use?

**Comment by romellfudi** [comment]
Hi @vovoapps, I solve the kotlin issues, now works correctly

**Comment by romellfudi** [comment]
Hi @vovoapps, I solve the kotlin issues, now it works correctly:
```
    implementation 'com.romellfudi.ussdlibrary:kotlin-ussd-library:1.1.k'
```

Also you need use different resources in your manifest file, check README file.

**Comment by ghyath5** [comment]
I am facing the same issue now in Kotlin

```
USSDController.callUSSDOverlayInvoke(
                    activity,
                    code,
                    map,
                    object : USSDController.CallbackInvoke {
                        override fun responseInvoke(message: String) {
                            Log.d(TAG, "USSD response: $message")
```



responseInvoke is never being called, the dial ussd command successfully called, but this function not fired
