### ISSUE TITLE
App accessibility error

### ISSUE THREAD

**Issue by yann-yvan** [romellfudi/VoIpUSSD#34]
java.lang.SecurityException: Permission Denial: starting Intent { act=android.intent.action.CALL dat=tel:xxxxxxxxx flg=0x10000000 cmp=com.android.server.telecom/.components.UserCallActivity (has extras) }

this occurs after permission grant

**Comment by yann-yvan** [comment]
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.content.Context.getSystemService(java.lang.String)' on a null object reference
        at com.romellfudi.ussdlibrary.USSDController.isAccessiblityServicesEnable(USSDController.java:280)
        at com.romellfudi.ussdlibrary.USSDController.verifyAccesibilityAccess(USSDController.java:202)
        at com.romellfudi.ussdlibrary.USSDController.callUSSDInvoke(USSDController.java:101)
        at com.romellfudi.ussdlibrary.USSDController.callUSSDInvoke(USSDController.java:74)

**Comment by yann-yvan** [comment]
Here is my code

USSDController.verifyAccesibilityAccess(this);
        HashMap map = new HashMap<>();
        USSDApi ussdApi;
        map.put("KEY_LOGIN", new HashSet<>(Arrays.asList("espere", "waiting", "loading", "esperando")));
        map.put("KEY_ERROR", new HashSet<>(Arrays.asList("problema", "problem", "error", "null")));
        ussdApi = USSDController.getInstance(this);
        ussdApi.callUSSDInvoke("#99#", map, new USSDController.CallbackInvoke() {
            @Override
            public void responseInvoke(String message) {
                // message has the response string data
                String dataToSend = "0";// <- notifyTaskComplete "data" into USSD's input text
            }

            @Override
            public void over(String message) {
                // message has the response string data from USSD or error
                // response no have input text, NOT SEND ANY DATA
            }
        });

**Comment by romellfudi** [comment]
Did you add xml? Or ask user to allow ussdservice permissions?

**Comment by yann-yvan** [comment]
<?xml version="1.0" encoding="utf-8"?>
<accessibility-service xmlns:android="http://schemas.android.com/apk/res/android"
    android:accessibilityEventTypes="typeWindowStateChanged"
    android:packageNames="com.android.phone"
    android:accessibilityFeedbackType="feedbackGeneric"
    android:accessibilityFlags="flagDefault"
    android:canRetrieveWindowContent="true"
    android:description="@string/accessibility_service_description"
    android:notificationTimeout="0"/>
    

and the manifest permission

<uses-permission android:name="android.permission.READ_PHONE_STATE"/>
    <uses-permission android:name="android.permission.CALL_PHONE" />
    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW" />

**Comment by romellfudi** [comment]
Fork and update code , to go over it

**Comment by romellfudi** [comment]
These errors happen when you ask the accessibility service is installed & enabled

**Comment by romellfudi** [comment]
@yann-yvan, did you work it out?

**Comment by romellfudi** [comment]
@yann-yvan can you update your code or send a gift?

**Comment by yann-yvan** [comment]
Hi finaly i got the problem
I where sending a null context iI catch out the error after trying to debug your code
I'm **Really sorry** about that
Greate Job it work's perfectly
Thank's

**Comment by romellfudi** [comment]
I recently created a ussd-community chat  please join: https://gitter.im/romellfudi/VoIpUSSD .
