### ISSUE TITLE
Programmatically close dialog

### ISSUE THREAD

**Issue by dammynex** [romellfudi/VoIpUSSD#35]
Some USSD codes last response includes the input box which does not let the dialogs close after last response.

Can you please add an option to close dialog programmatically. Thanks

**Comment by romellfudi** [comment]
Attach a video o gif

**Comment by dammynex** [comment]
Here is an example:

![ezgif-4-89b76e42ce50](https://user-images.githubusercontent.com/30000286/69959510-9c551f00-1507-11ea-8af7-e8935c9f5594.gif)

**Comment by romellfudi** [comment]
I understand you, that isn't an issue.
i will try to do it , as soon as possible (maybe in weekend).
However i think you close incorrectly the USSD GATEWAY

**Comment by romellfudi** [comment]
@dammynex , Whats happen when you send other number?

**Comment by romellfudi** [comment]
@dammynex , I recommend adding in your [frok code](https://github.com/dammynex/VoIpUSSD) a method (close):
```java
public interface USSDApi {
    void close();
}
USSDController:
public static void close() {
    USSDService.close();
}
USSDService:
public static void close() {
        clickOnButton(event, 0);
    }
```

And thats it

**Comment by romellfudi** [comment]
Hi @dammynex , it solves, cancel method
