### ISSUE TITLE
Oreo accessibility lifecycle issue

### ISSUE THREAD

**Issue by buFFalo94** [romellfudi/VoIpUSSD#37]
On android Oreo OnServiceConnected is only called when you toggle on accessibility service for the first time  thus the app will only work once, If you want to make it work again you'll need to reboot your device or to disable accessibility and enable it again

**Comment by romellfudi** [comment]
Mm... that happens when don't close correctly.  You last action must be over() method

**Comment by buFFalo94** [comment]
Oh sorry I tested on Pie 
It's works on lollipop and Nougat
I've read on stackoverflow that it's happen on Oreo too

**Comment by buFFalo94** [comment]
Even if you close it correctly, the next time it's won't work unless you reboot the phone or disabled and enable it again

**Comment by romellfudi** [comment]
M.mm...I don't think so, maybe it's a flag into library.  Tell me only happens on Pie?

**Comment by buFFalo94** [comment]
Yeah only pie

**Comment by buFFalo94** [comment]
I got more time to test on different phones running Pie, it's seems like a running some others but the issue persist on others. Note that the issue does not seems to affect phones like Pixel which does not uses custom android OS

**Comment by romellfudi** [comment]
Hi @buFFalo94  Please send me the log (tag: USSDService)
mmm... please use branch 'settings' instead of network library.
allprojects {
		repositories {
			maven { url 'https://jitpack.io' }
		}
	}
implementation 'com.github.romellfudi.VoIpUSSD:kotlin-ussd-library:settings-Rev22-g41203f2-8'

**Comment by romellfudi** [comment]
@buFFalo94, i test several times in my emulator (Android Pie - 9)and it works correctly.
Try to check the USSD class activity with the library that I have [posted it](https://github.com/romellfudi/VoIpUSSD/issues/37#issuecomment-569271511) before

**Comment by buFFalo94** [comment]
> @buFFalo94, i test several times in my emulator (Android Pie - 9)and it works correctly.
> Try to check the USSD class activity with the library that I have [posted it](https://github.com/romellfudi/VoIpUSSD/issues/37#issuecomment-569271511) before
Emulator never completely kill a process that's why it's seems to work but on actual device it's works but if you clean up running apps accessibility service will stop to work until next phone reboot
You can make it work by disabling and enabling again the accessibility service

**Comment by romellfudi** [comment]
On Samsung 8+ with Pie works very well, on Pixel which class name of ussd activity uses

**Comment by TigranSarkisian** [comment]
unfortunately still esxists on real device (sumsung s8 android 9)

**Comment by romellfudi** [comment]
@TigranSarkisian tell me the class name.
