### ISSUE TITLE
How to fix flashing window?

### ISSUE THREAD

**Issue by xwiz** [romellfudi/VoIpUSSD#4]
Hi, great work here. Do you have any idea how to fix the window that flashes and disappears?

**Comment by romellfudi** [comment]
Well, It not directly possible, thats Windows are builded by OS, so its has high privileges, thats the reason i  OverlayShowingService class (worked at Android O), but now its imposible hide or resize.

**Comment by xwiz** [comment]
Hi romellfudi, I figured out how to put the overlay but there still seems to be a flash just immediately during the dial. It seems Hover SDK has figured out how to complete hide everything. I am wondering if using an outgoing call receiver will solve it but it looks like too much work for a small feature

**Comment by xwiz** [comment]
I just saw one here @romellfudi : https://github.com/jumaallan/Hover

But it's pretty simple https://www.usehover.com/docs, I'm just curious how it works.

**Comment by romellfudi** [comment]
@xwiz What 'steps' do you think put in Hover Api?
<img width="499" alt="screen shot 2018-10-25 at 8 50 44 am" src="https://user-images.githubusercontent.com/1668017/47505123-232ec700-d833-11e8-905a-23b15b576e2d.png">

**Comment by xwiz** [comment]
Uh it's not required to test it but it just means like ussd input response.

**Comment by romellfudi** [comment]
always show Action Not found

**Comment by xwiz** [comment]
Did you sign up on usehover? You have to sign up and create action https://www.usehover.com/docs/actions

**Comment by romellfudi** [comment]
ok, i resolved, let me see your code, how navigate for all windows, you could put your code here?

**Comment by xwiz** [comment]
navigate for all windows?

**Comment by xwiz** [comment]
The goal of hover is so that you don't have to do that. You just do everything in [one line of code.](https://github.com/jumaallan/Hover/blob/master/app/src/main/java/com/androidstudy/hover/MainActivity.java#L35)

**Comment by romellfudi** [comment]
i am tried use this code, but i couldn't pass the first view:
                .extra("first", "1")
                .extra("second", "1")

**Comment by romellfudi** [comment]
Always return me "input requied"

**Comment by xwiz** [comment]
OK but does it send only one input successfully?

**Comment by romellfudi** [comment]
not

**Comment by romellfudi** [comment]
How do you define your `action_name `

**Comment by xwiz** [comment]
I think it's the first input on the create action page

**Comment by xwiz** [comment]
It's not very user friendly

**Comment by romellfudi** [comment]
My overlay its simple, if you wanna hide all windows, just extends and remove transparent transparent background, and setting what ever you want like a textColor, a gif, or what ever you need

**Comment by romellfudi** [comment]
My code better than Hover cuz its open source, so you could copy my OverlayShowingService and custom view, and set your custom layout like Hover.

**Comment by xwiz** [comment]
Yes, you are right. But there code is heavily tested. I was interested because they don't have any flashing window issues.

**Comment by romellfudi** [comment]
Hi @xwiz, i'm developing a new overlay class/ splash progressing screen

**Comment by romellfudi** [comment]
in Version 1.1,d you could use SplashLoadingService, this overlay widget hide completely all ussd windows:
- [SplashLoadingService](https://github.com/romellfudi/VoIpUSSD/raw/master/snapshot/device_splash.gif#gif)
