### ISSUE TITLE
Sim selection not working after update to android 10

### ISSUE THREAD

**Issue by aroaddy** [romellfudi/VoIpUSSD#41]
Hello good day, the library Simslot selection used to work perfectly in my app while the android version was 9.0. But after I updated the phone to Android 10, the phone always uses Sim slot 1 irrespective of what Sim number I choose for the ussdApi. Kindly help me resolve this issue.

**Comment by romellfudi** [comment]
Mmmm, right now, I don't have any devices for testing.  Are check how work sim cards in Android 10, don't hear that it had been changed

**Comment by romellfudi** [comment]
Hi @aroaddy, which model is your mobile phone?

**Comment by aroaddy** [comment]
It is Huawei Y9s, just realized that the Sim selection randomly works. That is sometimes it works perfectly and at other times it is fixed at Sim 1.

**Comment by romellfudi** [comment]
if it works, please download the module and debug USSDService class

**Comment by aroaddy** [comment]
alright many thanks

**Comment by romellfudi** [comment]
I update my android to Android 10 and it works normally without changing

**Comment by aroaddy** [comment]
Alright many thanks

**Comment by Nivekiba** [comment]
hello @romellfudi , no need to open the issue

I had a question, 
simslot indexing starts to 0 or 1?

**Comment by romellfudi** [comment]
0
