### ISSUE TITLE
Loop issues!

### ISSUE THREAD

**Issue by smpjsc1** [romellfudi/VoIpUSSD#5]
hi thanks for good work. i have problem hopefully you can help me.  
when i call multi send menu it loop send 1->2->1->2
it not call to 1->2->3
thank for read my english not good
> 

>  @Override
>     public void responseInvoke(String message) {
>         // first option list - select option 1
>         ussdController.send("1",new USSDController.CallbackMessage(){
>             @Override
>             public void responseMessage(String message) {
>                 // second option list - select option 1 
>                 ussdController.send("2",new USSDController.CallbackMessage(){
>                     @Override
>                     public void responseMessage(String message) {
>                         //  opntion - select otion 2 
                       ussdController.send("3",new USSDController.CallbackMessage(){
>                     @Override
>                     public void responseMessage(String message) {
>                         ...
>                     }
>                     }
>                 });
>             }
>         });
>     }

**Comment by romellfudi** [comment]
Its impossible, cuz when use ussdcontroller send method , the previously callback was drop out of stack, please give more information  abut the windows contained

**Comment by romellfudi** [comment]
Ensure the second response haven't KEY_login messages

**Comment by smpjsc1** [comment]
sorry for the delay. at my place 8 hours ago is 3 am.
Here is my code.
when i turn off the function clickOnButton
 ```
public static void send(String text) {
 setTextIntoField(event, text);
 // clickOnButton(event, 1);
 }
```
it auto input : 5->0999999999->
it not send 5->0999999999->8888888
```
ussdController.callUSSDInvoke(phoneNumber, map, new USSDController.CallbackInvoke() {
 @Override
 public void responseInvoke(String message) {
 Log.d("APP", message);
 result.append("\n-\n" + message);
 // first option list - select option 1
 ussdController.send("5", new USSDController.CallbackMessage() {
 @Override
 public void responseMessage(String message) {
 Log.d("APP", message);
 result.append("\n-\n" + message);
 // second option list - select option 1
 ussdController.send("0999999999", new USSDController.CallbackMessage() {
 @Override
 public void responseMessage(String message) {
 Log.d("APP", message);
 result.append("\n-\n" + message);
 ussdController.send("8888888", new USSDController.CallbackMessage() {
 @Override
 public void responseMessage(String message) {
 Log.d("APP", message);
 result.append("\n-\n" + message);
 }
 });
 }
 });
 }
 });
 }

 @Override
 public void over(String message) {
 Log.d("APP", message);
 result.append("\n-\n" + message);
 }
 });
```

**Comment by smpjsc1** [comment]
when click button 1: it send 5->09999999999->5->09999999999.
hope you help me
```
     btn1.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                String phoneNumber = phone.getText().toString().trim();
                final USSDController ussdController = USSDController.getInstance(getActivity());
                result.setText("");
                ussdController.callUSSDInvoke(phoneNumber, map, new USSDController.CallbackInvoke() {
                    @Override
                    public void responseInvoke(String message) {
                        Log.d("APP", message);
                        result.append("\n-\n" + message);
                        // first option list - select option 1
                        ussdController.send("5", new USSDController.CallbackMessage() {
                            @Override
                            public void responseMessage(String message) {
                                Log.d("APP", message);
                                result.append("\n-\n" + message);
                                // second input - input option 09999999999
                                ussdController.send("09999999999", new USSDController.CallbackMessage() {
                                    @Override
                                    public void responseMessage(String message) {
                                        Log.d("APP", message);
                                        result.append("\n-\n" + message);
										//third input - 888888
										ussdController.send("888888", new USSDController.CallbackMessage() {
											@Override
											public void responseMessage(String message) {
											Log.d("APP", message);
											result.append("\n-\n" + message);
											//fourth input 1
											ussdController.send("1", new USSDController.CallbackMessage() {
												@Override
												public void responseMessage(String message) {
													Log.d("APP", message);
													result.append("\n-\n" + message);
												}
											});
											}
										});
                                    }
                                });
                            }
                        });
                    }

                    @Override
                    public void over(String message) {
                        Log.d("APP", message);
                        result.append("\n-\n" + message);
                    }
                });
            }
        });
```

**Comment by smpjsc1** [comment]
> Ensure the second response haven't KEY_login messages , or add a stronger login string key to avoid containing login messages and avoid return invokeResponse
> 
> _Sent from my Galaxy S8+ using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

i think it's  problem for my case. how to fix it?

**Comment by smpjsc1** [comment]
my problem has solved thank you

**Comment by romellfudi** [comment]
@smpjsc1 Which telcom do you use it? and devices?, just for know.

**Comment by romellfudi** [comment]
@smpjsc1 i see  in a previous message your problem has solved, if you want help me just share my page or this project

**Comment by smpjsc1** [comment]
> @smpjsc1 Which telcom do you use it? and devices?, just for know.
when i comment it work for first call app. second run app it not send callback.
i use  samsung j2 for test
```
if (notInputText(event)) {
                // not more input panels / LAST MESSAGE
                // sent 'OK' button
                clickOnButton(event, 0);
                USSDController.instance.callbackInvoke.over(response);
            } else {
                // sent option 1
                if (USSDController.instance.callbackMessage == null)
                    USSDController.instance.callbackInvoke.responseInvoke(response);
                else {
                    USSDController.instance.callbackMessage.responseMessage(response);
                //    USSDController.instance.callbackMessage = null; 
                }
            }
```

**Comment by smpjsc1** [comment]
> @smpjsc1 i see in a previous message your problem has solved, if you want help me just share my page or this project
it's work for me in first run app.
```
if (notInputText(event)) {
                // not more input panels / LAST MESSAGE
                // sent 'OK' button
                clickOnButton(event, 0);
                USSDController.instance.callbackInvoke.over(response);
            } else {
                // sent option 1
                if (USSDController.instance.callbackMessage == null)
                    USSDController.instance.callbackInvoke.responseInvoke(response);
                else {
                    USSDController.instance.callbackMessage.responseMessage(response);
// it work for first build app
                //    USSDController.instance.callbackMessage = null; 
                }
            }
```

**Comment by romellfudi** [comment]
mmmm i resolved that issue, its happens when you dont finish correctly your previous call. Always need the last page (a page dont have input text). I dont add that patch, because when your work with ussd you will need add that requirements on TELCOM server. Other way its add a simple method that click at 'CANCEL' button

**Comment by lolobll** [comment]
> 
> 
> > @smpjsc1 i see in a previous message your problem has solved, if you want help me just share my page or this project
> > it's work for me in first run app.
> 
> ```
> if (notInputText(event)) {
>                 // not more input panels / LAST MESSAGE
>                 // sent 'OK' button
>                 clickOnButton(event, 0);
>                 USSDController.instance.callbackInvoke.over(response);
>             } else {
>                 // sent option 1
>                 if (USSDController.instance.callbackMessage == null)
>                     USSDController.instance.callbackInvoke.responseInvoke(response);
>                 else {
>                     USSDController.instance.callbackMessage.responseMessage(response);
> // it work for first build app
>                 //    USSDController.instance.callbackMessage = null; 
>                 }
>             }
> ```

I was able to resolve this but returning null after result.append("\n-\n" + message);
