### ISSUE TITLE
Third Option not working

### ISSUE THREAD

**Issue by trimmytech** [romellfudi/VoIpUSSD#54]
third option not working

 ussdApi.callUSSDInvoke("*555#", map, new USSDController.CallbackInvoke() {

                    @Override
                    public void responseInvoke(String message) {
                        //

                        ussdApi.send("4",new USSDController.CallbackMessage(){
                            @Override
                            public void responseMessage(String message) {
                               
                                // second option list - select option 1
                                ussdApi.send("3",new USSDController.CallbackMessage(){
                                    @Override
                                    public void responseMessage(String message) {
                                        //
                                    }
                                });

                              

                              

                            }
                        });
                        ussdApi.cancel();

                    }

                    @Override
                    public void over(String message) {

            

                    }

                });

**Comment by romellfudi** [comment]
@trimmytech , this library depends on Android OS version, in many cases fix it using using the `alternative branch`:
```gradle
    implementation 'com.github.romellfudi.VoIpUSSD:ussd-library:alternative-SNAPSHOT'
    implementation 'com.github.romellfudi.VoIpUSSD:kotlin-ussd-library:alternative-SNAPSHOT'
```

**Comment by romellfudi** [comment]
@trimmytech if you wants, u'll reopen

**Comment by contactBoostTag** [comment]
I use the alternative branch, thus work it out!

**Comment by trimmytech** [comment]
how can i use the alternative branch please ?

**Comment by trimmytech** [comment]
i am getting 

`Failed to resolve: com.github.romellfudi.VoIpUSSD:ussd-library:alternative-SNAPSHOT`

in gradle

**Comment by romellfudi** [comment]
You must add the maven repository:
maven { url 'https://jitpack.io' } into your  your project's build file
more detail [here](https://jitpack.io/#romellfudi/VoIpUSSD/alternative-SNAPSHOT)

**Comment by trimmytech** [comment]
still getting the sam error

     ```
   repositories {
        google()
        jcenter()
        maven { url 'https://maven.fabric.io/public' }
        maven { url 'https://jitpack.io' }
    }
```

**Comment by romellfudi** [comment]
Fork and share it. I have already tested it and works
