### ISSUE TITLE
rcursively creates callback

### ISSUE THREAD

**Issue by trimmytech** [romellfudi/VoIpUSSD#57]
This is a simple response code 

@Override
  public void responseInvoke(String message) {
 ussdApi.send("3",new USSDController.CallbackMessage(){
 @Override
 public void responseMessage(String message) {
  Log.d("trim_log", "3 entered \n\n"+message);
 }
   });

what i want to loop 3 times(dynamic , it might be more) and to produce like below code using for loop

@Override
public void responseInvoke(String res) {
    ussdApi.send("1",new USSDController.CallbackMessage(){
            //
        @Override
   public void responseMessage(String ms) {
        Log.d("trim_log", "1 entered");
        //
        ussdApi.send("2",new USSDController.CallbackMessage(){
                //
            @Override
   public void responseMessage(String ms) {
            Log.d("trim_log", "2 entered");
            //
            ussdApi.send("3",new USSDController.CallbackMessage(){
                    //
                @Override
   public void responseMessage(String ms) {
                Log.d("trim_log", "3 entered");
            });
        });
    });

   }

???

**Comment by romellfudi** [comment]
try use alternative branch

**Comment by trimmytech** [comment]
i am using alternative branch already

**Comment by trimmytech** [comment]
can you please post like a sample snippet ?

**Comment by romellfudi** [comment]
@trimmytech , change your USSDService.java:
Instead of this:
https://github.com/romellfudi/VoIpUSSD/blob/18d4cf7a3dcbbdfb82151947b3bab0c1ae7309c4/ussd-library/src/main/java/com/romellfudi/ussdlibrary/USSDService.java#L76
use the 5 following lines
https://github.com/romellfudi/VoIpUSSD/blob/23236ba38568e2defb4d47efb14dcb8177a6561c/ussd-library/src/main/java/com/romellfudi/ussdlibrary/USSDService.java#L70

**Comment by romellfudi** [comment]
Did you solve?

**Comment by romellfudi** [comment]
@trimmytech did you modify your flow as to finish the workflow

**Comment by romellfudi** [comment]
@trimmytech In 1.2.a , it works perfectly
