### ISSUE TITLE
Default Activity not found

### ISSUE THREAD

**Issue by hadepea16** [romellfudi/VoIpUSSD#58]
Dear romelfudi,

I want to use your library into my project,
but when i insert your library into my dependencied, then what is caused my android studio say that
default activities doesnt found ? (i'd checked my androidmanifest, but i cant found the problem from my side)
please your help...

thank you
![Capture](https://user-images.githubusercontent.com/11378578/91123859-1944ac00-e6c8-11ea-8294-a20e4967c907.PNG)

**Comment by romellfudi** [comment]
It's very difficult to know at first.
Nonetheless, my library works as any other open-source module

**Comment by hadepea16** [comment]
Hi romelfudi,

it's look like a little bug on my side, now your library is works well on my project..
thank you for this cool library !
