### ISSUE TITLE
Problem with ussd

### ISSUE THREAD

**Issue by victors0991** [romellfudi/VoIpUSSD#6]
I download your app but I want to get information about service of LTE of my cellphone so I put *#0011# and that doesnt work but it works when I put that ussd un my cell without app

**Comment by victors0991** [comment]
That code is to open service mode an I can see Lte parametters

**Comment by victors0991** [comment]
For example
I dial *#0011# and automatically appaear the windows that I show in image above
![image](https://user-images.githubusercontent.com/34872326/49701411-1505f180-fbba-11e8-979b-f5d42244e560.png)

**Comment by romellfudi** [comment]
Interesting

**Comment by victors0991** [comment]
I do not know , but you must have a code for view your lte connection

**Comment by victors0991** [comment]
![image](https://user-images.githubusercontent.com/34872326/49703653-9d45c000-fbd5-11e8-8a7c-43b103507e1e.png)

**Comment by romellfudi** [comment]
@victors0991 i dont understand clearly, cuz my telcom on my device worked different, so if could recored your screen or make a gif with your sentence. To improve the code and help other people from around the world

**Comment by victors0991** [comment]
mmm I do not understand, You do it?? or dont

**Comment by romellfudi** [comment]
You need change XML for read whatever android's widgets , and then  call that'll "secret code" . May be I'll do it later on other repository. : Android using secret codes

**Comment by victors0991** [comment]
ok, Last question, can you give me a explain me what do I need to do i order to get my goals please?

**Comment by romellfudi** [comment]
Not looking "service mode" , seek how implement "secret codes on android
