### ISSUE TITLE
Final USSD dialog message showing on top of Splash Screen

### ISSUE THREAD

**Issue by bensonokiora** [romellfudi/VoIpUSSD#67]
Am trying to run a multi-step USSD which works fine but a final dialog message pops up for milliseconds before the service terminates it. Is there a way to hide it since it's disrupting the UI
![Screenshot_20210302-120540](https://user-images.githubusercontent.com/12033587/109625903-eedd1b00-7b50-11eb-881c-9e2b3250a20e.jpg)

https://user-images.githubusercontent.com/12033587/109626026-13d18e00-7b51-11eb-914c-8d45cff9eca1.mp4

**Comment by romellfudi** [comment]
Does the splash dismiss or not?

**Comment by romellfudi** [comment]
No no no

**Comment by romellfudi** [comment]
In my humble view, is that message the final response or are you you waiting for more incoming windows?

**Comment by bensonokiora** [comment]
That's the final response. The splash-dialog is dismissed immediately after. But the final response is still showing on top of the splash-dialog

**Comment by romellfudi** [comment]
which part of your code it's stopped, over method?

**Comment by bensonokiora** [comment]
I have tried the cancel method in over method. Still not working 

`ussdApi.callUSSDOverlayInvoke(phoneNumber, map, new USSDController.CallbackInvoke() {
                        @Override
                        public void responseInvoke(String message) {
                            Log.d("APP", message);
                            binding.result.append("\n-\n" + message);
                            // first option list - select option 1
                            ussdApi.send("6", new USSDController.CallbackMessage() {
                                @Override
                                public void responseMessage(String message) {
                                    Log.d("APP", message);
                                    binding.result.append("\n-\n" + message);
                                    // second option list - select option 2
                                    ussdApi.send("1", new USSDController.CallbackMessage() {
                                        @Override
                                        public void responseMessage(String message) {
                                            Log.d("APP", message);
                                            binding.result.append("\n-\n" + message);
                                            // second option list - select option 1
                                            ussdApi.send("883927", new USSDController.CallbackMessage() {
                                                @Override
                                                public void responseMessage(String message) {
                                                    Log.d("APP", message);
                                                    binding.result.append("\n-\n" + message);
                                                    ussdApi.send("test1", new USSDController.CallbackMessage() {
                                                        @Override
                                                        public void responseMessage(String message) {
                                                            Log.d("APP", message);
                                                            binding.result.append("\n-\n" + message);
                                                            ussdApi.send("1", new USSDController.CallbackMessage() {
                                                                @Override
                                                                public void responseMessage(String message) {
                                                                    Log.d("APP", message);
                                                                    binding.result.append("\n-\n" + message);
                                                                    ussdApi.send("1590", new USSDController.CallbackMessage() {
                                                                        @Override
                                                                        public void responseMessage(String message) {
                                                                            Log.d("APP", message);
                                                                            binding.result.append("\n-\n" + message);
                                                                            ussdApi.send("1", new USSDController.CallbackMessage() {
                                                                                @Override
                                                                                public void responseMessage(String message) {
                                                                                    Log.d("APP", message);
                                                                                    binding.result.append("\n-\n" + message);
                                                                                    ussdApi.cancel();
                                                                                    getActivity().stopService(svc);

                                                                                }
                                                                            });
                                                                        }
                                                                    });
                                                                }
                                                            });
                                                        }
                                                    });
                                                }
                                            });
                                        }
                                    });
                                }
                            });
                        }

                        @Override
                        public void over(String message) {
                            Log.d("APP", message);
                            binding.result.append("\n-\n" + message);
                            ussdApi.cancel();
                            getActivity().stopService(svc);
                            Log.d("APP", "STOP OVERLAY DIALOG");
                        }
                    });`

**Comment by romellfudi** [comment]
Drop ussdApi.cancel() line, why do you put in that line?

**Comment by bensonokiora** [comment]
I have deleted them, still no changes. I only added them to try to solve the problem
```
ussdApi.callUSSDOverlayInvoke(phoneNumber, map, new USSDController.CallbackInvoke() {
                        @Override
                        public void responseInvoke(String message) {
                            Log.d("APP", message);
                            binding.result.append("\n-\n" + message);
                            // first option list - select option 1
                            ussdApi.send("1", new USSDController.CallbackMessage() {
                                @Override
                                public void responseMessage(String message) {
                                    Log.d("APP", message);
                                    binding.result.append("\n-\n" + message);

                                   
                                   
                                }
                            });
                            
                        }

                        @Override
                        public void over(String message) {
                            Log.d("APP", message);
                            binding.result.append("\n-\n" + message);
                            

                            getActivity().stopService(svc);
                            Log.d("APP", "STOP OVERLAY DIALOG");
                        }
                    });
```

**Comment by romellfudi** [comment]
Put a delay before dismiss the splash

**Comment by bensonokiora** [comment]
Is this what you mean? added a delay on over method. still no changes

```
ussdApi.callUSSDOverlayInvoke(phoneNumber, map, new USSDController.CallbackInvoke() {
                        @Override
                        public void responseInvoke(String message) {
                            Log.d("APP", message);
                            binding.result.append("\n-\n" + message);
                            // first option list - select option 1
                            ussdApi.send("1", new USSDController.CallbackMessage() {
                                @Override
                                public void responseMessage(String message) {
                                    Log.d("APP", message);
                                    binding.result.append("\n-\n" + message);

                                   
                                   
                                }
                            });
                            
                        }

                        @Override
                        public void over(String message) {
                            Log.d("APP", message);
                            binding.result.append("\n-\n" + message);
                            

                         final Handler handler = new Handler();
                            handler.postDelayed(new Runnable() {
                                @Override
                                public void run() {
                                    getActivity().stopService(svc);
                                    Log.d("APP", "STOP OVERLAY DIALOG");
                                }
                            }, 3000);

                        }
                    });
```

**Comment by bensonokiora** [comment]
Is there a way to set the Splash Screen  `WindowManager.LayoutParams` at topmost of any dialog prompted by the USSD response?

**Comment by romellfudi** [comment]
It's been set. Could you say me the last ussdDialog never dismiss?

**Comment by bensonokiora** [comment]
The last ussdDialog  is dismissed

**Comment by bensonokiora** [comment]
The problem is it still pops up in-front of the Splash screen before being dismissed by the over method

**Comment by romellfudi** [comment]
ouhmmm....You must communicate with Google developer teams on the grounds that they know why the last dialog has overlayPermission too.

When they reply to you please re-open this issue

**Comment by romellfudi** [comment]
* The last dialog might have had overlayShowing permissions

* You must communicate with Google developer teams on the grounds that they know why the last dialog has overlayPermission too; Besides, ask whether you could change the attributes of that kind of dialogs

When they reply to you please re-open this issue. 
please keep me updated
