### ISSUE TITLE
how to pass extra data in action_call intent

### ISSUE THREAD

**Issue by ducaale** [romellfudi/VoIpUSSD#8]
for example if we want to use second sim `intent.putExtra("com.android.phone.extra.slot", 1);`

**Comment by romellfudi** [comment]
Hi @ducaale ,like any call put the extra data before start  dial-up, but not worked at some smartphones[, [1]](https://stackoverflow.com/questions/13231962/call-from-second-sim/19474441#19474441), my api doesnt work directly with the SIM card, its that i dont put it a special parameter.

**Comment by ducaale** [comment]
so should i replace `ussdController.callUSSDInvoke` with normal action_call intent then call `ussdController.send` ?

**Comment by ducaale** [comment]
what if an overloaded `ussdController.callUSSDInvoke` is added that accepts call intent instead of phone number

**Comment by romellfudi** [comment]
Did You code? I'll test the puĺl requests to some devives

**Comment by romellfudi** [comment]
Did You code? I'll test the puĺl requests to some devives

**Comment by romellfudi** [comment]
its just a tip: create a temp branch(with your commits) before create a pull request to test more quickly
