### ISSUE TITLE
how to make instance in kotlin ? 

### ISSUE THREAD

**Issue by raykibul** [romellfudi/VoIpUSSD#97]
USSDApi ussdApi = USSDController.getInstance(context);

I tried var ussdApi : USSDApi = USSDController.instance

I am using   USSDController.callUSSDInvoke(context .....
is this the way?

**Comment by romellfudi** [comment]
Yes, "this is the way"✨

**Comment by romellfudi** [comment]
@raykibul Could you implement the library in your project?

**Comment by raykibul** [comment]
Yes ! thank you <3
